# tf Tensors and Numpy arrays

In [3]:
import numpy as np
import tensorflow as tf

In [4]:
M_tf = tf.constant([[1,2,3],[4,5,6]])
M_np = np.array([[1,2,3],[4,5,6]])
print(M_tf)
print(M_np)
print(M_tf[:,1])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
[[1 2 3]
 [4 5 6]]
tf.Tensor([2 5], shape=(2,), dtype=int32)


Conversion np <-> tf

In [5]:
n = np.array([[1,2,3],[4,5,6]])
t = tf.constant([[1,2,3],[4,5,6]])
n_to_t = tf.constant(n)
t_to_n = np.array(t)
print(n_to_t)
print(t_to_n)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
[[1 2 3]
 [4 5 6]]


On ne peut pas additionner des tenseurs de type différent

In [6]:
tf.constant(2.)+tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 

Il faut les convertir

In [11]:
tf2 = tf.constant(2.0,dtype=tf.float32)
tf40 = tf.constant(40)
tf42 = tf2 + tf.cast(tf40,tf.float32)
print(tf42)

tf.Tensor(42.0, shape=(), dtype=float32)


Les valeurs de tf.constant ne sont pas modifiables:

In [19]:
t = tf.constant([[1,2,3],[4,5,6]])
t[0,0].assign(3)


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Utiliser tf.variable si on veut pouvoir modifier ce qui est contenu

In [23]:
t = tf.Variable([[1,2,3],[4,5,6]])
t[0,0].assign(3) # change one element
t[:,1].assign([10,10]) # change a column
t.scatter_nd_update(indices=[[0,2],[1,2]],updates=[200,200]) # change by indices
t.assign(2*t) # change the whole array
print(t)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[  6,  20, 400],
       [  8,  20, 400]])>
